version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc --go_out=./pkg/protos --go_opt=paths=source_relative --go-grpc_out=./pkg/protos --go-grpc_opt=paths=source_relative ./api/auth/*proto